### ISSUE TITLE
百度网盘使用refresh_token刷新token的方式无法正常访问

### ISSUE THREAD

**Issue by FantasyKingdom** [alexiscn/CloudServiceKit#10]
你好，作者，我用demo试了下百度网盘，貌似不能采取每次登陆都刷新refresh_token的方式进行登陆，每次去刷新token的时候会返回-10错误。但是用首次登陆返回的token能正常登陆成功。你那边有没有遇到这个问题。

**Comment by alexiscn** [comment]
according the document https://pan.baidu.com/union/doc/al0rwqzzl

> Access Token 有效期30天，过期后支持刷新，刷新后的 Access Token 有效期仍为 30 天，刷新Access Token请按需刷新，不需要不停的刷新。
>
> 刷新请求，如果API返回失败，旧的refresh_token会失效，此时需要重新发起授权请求，获取新的 Access Token、refresh_token，而不是使用旧的 refresh_token 循环再发起刷新请求。
>
> refresh_token 只支持使用一次，refresh_token 使用后失效，下次刷新 Access Token 时需要使用上一次刷新请求响应中的 refresh_token。

We need to use refresh_code when access token expired, not everytime we sign in.

I will update the sample project when I have spare time.

**Comment by alexiscn** [comment]
Updated example fixing refresh access token issue with commit 3820c76b60ccb63f83cb5903e34d373bbfa144f7, please check it.

**Comment by FantasyKingdom** [comment]
感谢作者！
