### ISSUE TITLE
您好,demo 跑起来了,但是没跳转到文件列表页面呢

### ISSUE THREAD

**Issue by freddiezhao** [alexiscn/CloudServiceKit#11]
demo 跑起来了,但是没跳转到文件列表页面呢,直接在 webview 里面打开了授权回调的URL了,然后就没有任何反应了,

这里也没有任何的事件被捕捉到:  

    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        
        guard let url = URLContexts.first?.url else {
            return
        }
        if url.host == "https://test.aliyundrive.com" {
            OAuthSwift.handle(url: url)
        }
    }

![IMG_7406](https://github.com/user-attachments/assets/51b17929-c2c7-4b97-9adc-bdade195c3e9)

**Comment by alexiscn** [comment]
fixed in commit 763d3eb6f572e364f7b72601fc53536222d2c8c0

**Comment by freddiezhao** [comment]
> fixed in commit [763d3eb](https://github.com/alexiscn/CloudServiceKit/commit/763d3eb6f572e364f7b72601fc53536222d2c8c0)

非常感谢,已经可以正常跳转了,再次感谢您及时的回复.
