### ISSUE TITLE
流程搞完了,请问有批量上传的支持么

### ISSUE THREAD

**Issue by birdmichael** [alexiscn/CloudServiceKit#3]

**Comment by alexiscn** [comment]
这个是具体业务逻辑了，应该由业务方自行实现，调用上传接口就可以了。

业务方需要处理列表、维护状态、以及处理后台上传。

目前貌似不支持后台上传，你可以fork 后自行修改。

**Comment by birdmichael** [comment]
嗯嗯.在改了...谢谢..
我发现这个真的验证了await 的重要...目前我这边的操作包了无数层了,正在改await版
